# Generated by Django 4.1.1 on 2022-09-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='dates',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
